AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cognito User Pool'
Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: test-user-pool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: true
      MfaConfiguration: "ON"
      SmsConfiguration:
        ExternalId: "test-user-pool-sms-configuration"
        SnsCallerArn: "arn:aws:iam::718761849884:role/SNSCallerRole"
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: "verified_email"
            Priority: 1
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 30
      Schema:
        - Name: email
          Required: true
          Mutable: true
          AttributeDataType: String
        - Name: name
          Required: true
          Mutable: true
          AttributeDataType: String
        - Name: zone
          Required: false
          Mutable: true
          AttributeDataType: String
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
  
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: test-user-pool-client
      GenerateSecret: false
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
      - ALLOW_USER_PASSWORD_AUTH
      - ALLOW_REFRESH_TOKEN_AUTH
      - ALLOW_USER_SRP_AUTH

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: test-user-pool-domain-udcee
      UserPoolId: !Ref CognitoUserPool
